services:
  lgtm:
    image: grafana/otel-lgtm:0.8.1
    container_name: lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      GF_PATHS_DATA: /data/grafana
    volumes:
      - C:/Users/WiBla/Documents/Docker/grafana:/data/grafana
      - C:/Users/WiBla/Documents/Docker/prometheus:/data/prometheus
      - C:/Users/WiBla/Documents/Docker/loki:/data/loki
